
test_bank = {
    "Community-Present": {
        "Negation": [
            ("Patient denies living with anyone.", 0),
            ("No family at home.", 0),
            ("Lives alone.", 0),
            ("Patient not cohabitating.", 0),
            ("She has no immediate family living with her.", 0),
            ("No roommates or partners mentioned.", 0),
            ("Does not report living with others.", 0),
            ("Negative for shared housing.", 0),
            ("Lives by herself.", 0),
            ("Patient lives independently.", 0),
            ("He is without a support network at home.", 0),
            ("No mention of family in household.", 0),
            ("Patient states she lives alone.", 0),
            ("Not currently living with friends or family.", 0),
            ("No caregiver or roommate mentioned.", 0),
            ("Does not live with children.", 0),
            ("No domestic partners reside with her.", 0),
            ("Patient has no known cohabitants.", 0),
            ("Reports living in isolation.", 0),
            ("States 'I live alone'.", 0),
        ],
        "Misspellings": [
            ("Patient ilves with her grandson.", 1),
            ("She lifes with her husband.", 1),
            ("Stays wth her son.", 1),
            ("Currntly livng with partner.", 1),
            ("Livs in a househld with two siblings.", 1),
            ("She shres a room with cousin.", 1),
            ("She is cohabitatng with daughter.", 1),
            ("She stays wih her kids.", 1),
            ("Living wth close friend.", 1),
            ("He is residng with spouse.", 1),
            ("Currenly cohabitng.", 1),
            ("Resdes with parents.", 1),
            ("He livs with his dog and roommate.", 1),
            ("They shre an apartment.", 1),
            ("Lives wit family.", 1),
            ("Family live withh him.", 1),
            ("Co-habiting wih nephew.", 1),
            ("Shars space with brother.", 1),
            ("He’s not alne — partner with him.", 1),
            ("Kids live in same home.", 1),
        ]
    },

    "Community-Absent": {
        "Negation": [
            ("She lives with her husband and child.", 1),
            ("Currently cohabiting with partner.", 1),
            ("Lives with roommate.", 1),
            ("Staying with parents.", 1),
            ("Patient shares household with wife.", 1),
            ("Living in multigenerational home.", 1),
            ("Lives with family members.", 1),
            ("She is not alone at home.", 1),
            ("He’s living with friends.", 1),
            ("Resides with extended family.", 1),
            ("Support system is present in household.", 1),
            ("Lives with elderly mother.", 1),
            ("Not living alone.", 1),
            ("Has help at home.", 1),
            ("Household includes relatives.", 1),
            ("Wife and kids share address.", 1),
            ("Domestic partner lives with him.", 1),
            ("Roommate sleeps in same house.", 1),
            ("Has cohabitants.", 1),
            ("Patient reports others in home.", 1),
        ],
        "Misspellings": [
            ("Patient is separtaed from his wife.", 1),
            ("Child lving elsewhere.", 1),
            ("Divrced and living alone.", 1),
            ("Not in contact wih family.", 1),
            ("Currently alne.", 1),
            ("N family present.", 1),
            ("No husemates or kin nearby.", 1),
            ("Family estranged — none in house.", 1),
            ("Wife mooved out.", 1),
            ("Son lives ovrseas.", 1),
            ("Spouse no longer residng with him.", 1),
            ("Not cohbiting.", 1),
            ("Apart frm relatives.", 1),
            ("Wife left — now isolted.", 1),
            ("No suppot system.", 1),
            ("Alone and frgotten.", 1),
            ("Isolatd livng.", 1),
            ("No kin rside here.", 1),
            ("Separated frm dependents.", 1),
            ("Living by slef.", 1),
        ]
    },
    "Education": {
        "Attribution": [
            ("Daughter is a college graduate.", 0),
            ("Her son has a PhD in chemistry.", 0),
            ("Wife teaches at a university.", 0),
            ("Sister is pursuing her bachelor's.", 0),
            ("Brother is enrolled in law school.", 0),
            ("Roommate just completed high school.", 0),
            ("Mother is a retired teacher.", 0),
            ("Father works as a professor.", 0),
            ("Spouse has an MBA.", 0),
            ("Daughter is a medical student.", 0),
            ("His girlfriend has no degree.", 0),
            ("Nephew is studying in college.", 0),
            ("Aunt works in an elementary school.", 0),
            ("Daughter-in-law is in graduate school.", 0),
            ("Sister-in-law teaches English.", 0),
            ("His cousin dropped out of college.", 0),
            ("Brother-in-law recently graduated.", 0),
            ("His nanny holds a BA.", 0),
            ("Her husband is completing his PhD.", 0),
            ("Spouse is a teacher.", 0)
        ],
        "Misspellings": [
            ("His daugter is a cllege gradute.", 0),
            ("Sonn is completting doctral program.", 0),
            ("Wief teches at univesity.", 0),
            ("Sistter pursing bachelors.", 0),
            ("Brothr enrollled in law shcool.", 0),
            ("Rommate gradueted high scool.", 0),
            ("Mothr is retired tacher.", 0),
            ("Fathr is profesorr.", 0),
            ("Spuose got MBA degree.", 0),
            ("Medcal studnt is dughter.", 0),
            ("Girlfrend not edcated.", 0),
            ("Nepw is in colledge.", 0),
            ("Ant teches elemntary.", 0),
            ("Daughtr-inlaw grad schhol.", 0),
            ("Sis-inlaw teches Englesh.", 0),
            ("Cousin droped out off colage.", 0),
            ("Brthr-inlaw just gradated.", 0),
            ("Nany has B A.", 0),
            ("Husbund is compliting Ph D.", 0),
            ("Spoose techer.", 0)
        ]
    },

    "Economics": {
        "Negation": [
            ("No job currently.", 0),
            ("Unemployed at the moment.", 0),
            ("He is not working.", 0),
            ("No income reported.", 0),
            ("Patient has no known employment.", 0),
            ("No source of income.", 0),
            ("He is without work.", 0),
            ("Zero income stream.", 0),
            ("She’s currently jobless.", 0),
            ("Not earning any wages.", 0),
            ("No employment noted.", 0),
            ("Patient is not employed.", 0),
            ("Unemployed.", 0),
            ("Patient reports no job.", 0),
            ("He is living off savings.", 0),
            ("No employer listed.", 0),
            ("She has no recent paystubs.", 0),
            ("No proof of income.", 0),
            ("Not engaged in any job.", 0),
            ("Currently without income.", 0)
        ],
        "Attribution": [
            ("Daughter has a full-time job.", 0),
            ("Son works at a tech company.", 0),
            ("Wife earns money from consulting.", 0),
            ("Roommate is a software engineer.", 0),
            ("Spouse is employed.", 0),
            ("Daughter-in-law works at the hospital.", 0),
            ("Uncle has a steady income.", 0),
            ("His cousin is a financial advisor.", 0),
            ("Partner just got hired.", 0),
            ("Housemate has an office job.", 0),
            ("Friend works remotely.", 0),
            ("Dad is employed.", 0),
            ("Girlfriend makes money online.", 0),
            ("Aunt runs a bakery.", 0),
            ("Spouse has a part-time job.", 0),
            ("Mother works as a nurse.", 0),
            ("Brother is working full-time.", 0),
            ("Partner has two jobs.", 0),
            ("Father is retired but has pension.", 0),
            ("His child is employed.", 0)
        ],
        "Misspellings": [
            ("He is a retierd dentist.", 0),
            ("No employmnt infomation.", 0),
            ("Currntly jobles.", 0),
            ("Patient hhas no inome.", 0),
            ("No enrnings at this time.", 0),
            ("Unemplyed with no savngs.", 0),
            ("Patint has lost his jb.", 0),
            ("No income souce found.", 0),
            ("Not wrking rght now.", 0),
            ("Unempoyed indivdual.", 0),
            ("No eployment detils.", 0),
            ("He is not currntly earning.", 0),
            ("Zero finacial inflow.", 0),
            ("Jobless adn unnsupported.", 0),
            ("Has no wrk since last year.", 0),
            ("Wife no longer has work.", 0),
            ("Brother retried ealier this year.", 0),
            ("His frend supprts him financilly.", 0),
            ("Not in fomal employmnt.", 0),
            ("Incmeless at present.", 0)
        ]
    },

    "Environment": {
        "Negation": [
            ("He has a stable place to live.", 1),
            ("Currently not homeless.", 1),
            ("Patient resides in own home.", 1),
            ("Has permanent housing.", 1),
            ("No risk of losing housing.", 1),
            ("Lives in subsidized apartment.", 1),
            ("Staying in long-term shelter.", 1),
            ("Rents an apartment.", 1),
            ("Housing situation is stable.", 1),
            ("Owns a home.", 1),
            ("He is not displaced.", 1),
            ("Has not been evicted.", 1),
            ("No concern about shelter.", 1),
            ("Stable living conditions.", 1),
            ("Patient not at risk for homelessness.", 1),
            ("Has a long-term lease.", 1),
            ("Safe and secure housing.", 1),
            ("Not worried about eviction.", 1),
            ("Resident in consistent dwelling.", 1),
            ("He is well housed.", 1)
        ],
        "Attribution": [
            ("His daughter is homeless.", 0),
            ("Wife lost her apartment.", 0),
            ("Son lives on the street.", 0),
            ("Cousin is couch-surfing.", 0),
            ("His nephew has no home.", 0),
            ("Mother has unstable housing.", 0),
            ("Partner just evicted.", 0),
            ("Friend is homeless.", 0),
            ("Family member lost housing.", 0),
            ("Uncle lives in a tent.", 0),
            ("Brother has no fixed address.", 0),
            ("Daughter-in-law is between homes.", 0),
            ("Roommate kicked out.", 0),
            ("Father recently evicted.", 0),
            ("She said her mom is living in car.", 0),
            ("Spouse moved in with friends.", 0),
            ("Mother-in-law on the street.", 0),
            ("Niece staying in shelter.", 0),
            ("Aunt is housing insecure.", 0),
            ("Partner is homeless, not the patient.", 0)
        ],
        "Misspellings": [
            ("Homeelss, searching for apt.", 0),
            ("Livs in tempory shelter.", 0),
            ("Homelesss since fire.", 0),
            ("Housng unstble.", 0),
            ("No permenant residnce.", 0),
            ("Stayng in care.", 0),
            ("Risk of loosing home.", 0),
            ("No securr home.", 0),
            ("Sheltrd but temporay.", 0),
            ("Unabel to maintan housing.", 0),
            ("Expelled frm apartment.", 0),
            ("On verge of evction.", 0),
            ("He got no plce to live.", 0),
            ("Currntly displaced.", 0),
            ("Housin unstable.", 0),
            ("Living in car bcs no house.", 0),
            ("Temp accmmodation.", 0),
            ("Long term home is gone.", 0),
            ("Housed but not stabble.", 0),
            ("No fixt adress.", 0)
        ]
    },

    "Alcohol Use": {
        "Negation": [
            ("Negative for alcohol use.", 0),
            ("Denies drinking.", 0),
            ("Never consumed alcohol.", 0),
            ("Patient does not drink.", 0),
            ("No EtOH use reported.", 0),
            ("He strongly denies alcohol intake.", 0),
            ("No history of drinking.", 0),
            ("Patient abstains from alcohol.", 0),
            ("Zero alcohol consumption.", 0),
            ("She is not a drinker.", 0),
            ("Alcohol: none.", 0),
            ("No EtOH in the last decade.", 0),
            ("He doesn't drink.", 0),
            ("Never been intoxicated.", 0),
            ("No alcohol habit.", 0),
            ("Does not partake in EtOH.", 0),
            ("Patient refuses alcohol.", 0),
            ("She says she avoids EtOH.", 0),
            ("No alcohol history noted.", 0),
            ("EtOH negative.", 0)
        ],
        "Attribution": [
            ("Negative for EtOH. Son has history of alcohol abuse.", 0),
            ("Brother drinks occasionally. Patient does not.", 0),
            ("Patient abstains. Wife consumes alcohol.", 0),
            ("Daughter has EtOH issues. Patient sober.", 0),
            ("He avoids drinking; his partner doesn’t.", 0),
            ("Father is alcoholic. Patient is not.", 0),
            ("Patient denies EtOH use. Husband drinks daily.", 0),
            ("Mother has EtOH addiction. Patient abstinent.", 0),
            ("Lives with alcoholic spouse, denies drinking.", 0),
            ("Son in rehab. Patient doesn’t drink.", 0),
            ("Sister has drinking problem. Patient sober.", 0),
            ("Patient avoids EtOH. Family history present.", 0),
            ("EtOH negative. Brother is alcoholic.", 0),
            ("Patient claims sobriety despite family issues.", 0),
            ("No EtOH, but spouse has history.", 0),
            ("Denies drinking; son relapsed.", 0),
            ("Partner abuses alcohol, patient clean.", 0),
            ("Roommate drinks; patient does not.", 0),
            ("Grandfather alcoholic; patient abstains.", 0),
            ("Patient clean, despite family exposure.", 0)
        ],
        "Historical Phrases": [
            ("Was sober for a few months, but started drinking again.", 2),
            ("Former alcoholic, resumed drinking.", 2),
            ("Was abstinent, relapsed recently.", 2),
            ("Sober for years, began using again.", 2),
            ("Had stopped, now drinks socially.", 2),
            ("No EtOH for years, recently resumed.", 2),
            ("Was clean, now occasional use.", 2),
            ("Had history of EtOH, currently drinking.", 2),
            ("Recently resumed after long break.", 2),
            ("Stopped and restarted EtOH.", 2),
            ("Used to abstain, now relapsed.", 2),
            ("Was in recovery, now drinks.", 2),
            ("Sober 2 years, but started again.", 2),
            ("Went back to drinking.", 2),
            ("History of EtOH use, resumed.", 2),
            ("Former drinker, now present use.", 2),
            ("Clean for years, resumed.", 2),
            ("Stopped then restarted drinking.", 2),
            ("History of sobriety, now using.", 2),
            ("EtOH use resumed.", 2)
        ],
        "Misspellings": [
            ("He dneies any history of alcohol intake.", 0),
            ("Never drnks.", 0),
            ("No EtOH consmption.", 0),
            ("Pt abstans from alchohol.", 0),
            ("EtOH: nevr.", 0),
            ("Says she never driks.", 0),
            ("Alohol intake none.", 0),
            ("Never use alcholic bevrages.", 0),
            ("Drinks? Nver.", 0),
            ("Histry of not drinkng.", 0),
            ("Pt avoids alchol.", 0),
            ("No etoh evr.", 0),
            ("Pt don’t use etoh.", 0),
            ("Says no alchohol hx.", 0),
            ("Pt has nevr used alch.", 0),
            ("Nno ETOH noted.", 0),
            ("No drnking hx.", 0),
            ("Never usr of alcohol.", 0),
            ("EtOH: nada.", 0),
            ("Denis EtOH.", 0)
        ]
    },
    "Tobacco Use": {
        "Negation": [
            ("Patient denies tobacco use.", 0),
            ("No smoking history.", 0),
            ("Never smoked cigarettes.", 0),
            ("No tobacco use reported.", 0),
            ("He has never used tobacco.", 0),
            ("Patient is a nonsmoker.", 0),
            ("Tobacco: none.", 0),
            ("Denies use of any nicotine products.", 0),
            ("Negative for cigarette smoking.", 0),
            ("She does not use tobacco.", 0),
            ("Has never smoked.", 0),
            ("Non-smoker.", 0),
            ("No nicotine use.", 0),
            ("Reports no tobacco consumption.", 0),
            ("Does not partake in smoking.", 0),
            ("He never picked up smoking.", 0),
            ("No use of tobacco in any form.", 0),
            ("Tobacco history is negative.", 0),
            ("No evidence of smoking.", 0),
            ("Patient never used cigarettes.", 0)
        ],
        "Attribution": [
            ("Patient denies smoking, but wife smokes.", 0),
            ("Father uses cigars, patient does not.", 0),
            ("Roommate smokes; patient abstains.", 0),
            ("Brother is a smoker. Patient never tried.", 0),
            ("Daughter smokes daily. Patient is clean.", 0),
            ("Spouse addicted to nicotine; patient isn’t.", 0),
            ("Patient lives with smokers but doesn’t smoke.", 0),
            ("Mother has tobacco addiction. Patient does not.", 0),
            ("Denies use; partner smokes.", 0),
            ("Grandparent smokes; patient avoids it.", 0),
            ("Lives in smoking household but abstains.", 0),
            ("Family smokes around him. He is tobacco-free.", 0),
            ("Friends smoke, but patient does not.", 0),
            ("She avoids secondhand smoke from relatives.", 0),
            ("Patient denies any tobacco use despite family use.", 0),
            ("No tobacco; daughter uses vape.", 0),
            ("Spouse smokes heavily, patient does not.", 0),
            ("Patient’s roommate smokes. He abstains.", 0),
            ("Brother addicted to tobacco, not patient.", 0),
            ("Patient clean; lives with smokers.", 0)
        ],
        "Historical Phrases": [
            ("Quit smoking 5 years ago, recently restarted.", 2),
            ("Was smoke-free, but picked up smoking again.", 2),
            ("Stopped smoking, then relapsed.", 2),
            ("Back to smoking after years of abstinence.", 2),
            ("Recently resumed tobacco use.", 2),
            ("History of quitting, currently smoking.", 2),
            ("Relapsed smoker.", 2),
            ("Was a former smoker, now resumed.", 2),
            ("Restarted tobacco after long break.", 2),
            ("Previously quit, now uses cigarettes again.", 2),
            ("Smoked in the past, and again now.", 2),
            ("Recent smoker after years smoke-free.", 2),
            ("Patient was off tobacco, resumed.", 2),
            ("Resumed after being tobacco-free.", 2),
            ("History of smoking, now active user.", 2),
            ("Used to smoke, currently resumed.", 2),
            ("Restarted cigarette use.", 2),
            ("Returned to smoking recently.", 2),
            ("Tobacco use began again.", 2),
            ("Resumed smoking habit.", 2)
        ],
        "Misspellings": [
            ("Pt dneies smoking.", 0),
            ("Never smoks.", 0),
            ("No tobaco use.", 0),
            ("Nver smoked cigs.", 0),
            ("Pt not a smooker.", 0),
            ("Tobacoo: none.", 0),
            ("No nictine habit.", 0),
            ("Avoids tobaco.", 0),
            ("Denis any smoking.", 0),
            ("No smking hx.", 0),
            ("He dosn’t smoke.", 0),
            ("Histry of no smoking.", 0),
            ("Pt nevr used cigs.", 0),
            ("No cigarretes ever.", 0),
            ("Pt avoids all tabacco.", 0),
            ("N tobacco exposur.", 0),
            ("Never usd tobaco.", 0),
            ("Negativ for smoking.", 0),
            ("Doesnt use nicotin.", 0),
            ("Nno smoking ever.", 0)
        ]
    },
    "Drug Use": {
        "Negation": [
            ("Patient denies any drug use.", 0),
            ("No history of recreational drug use.", 0),
            ("Never used illicit substances.", 0),
            ("Negative for drug abuse.", 0),
            ("Denies marijuana or cocaine use.", 0),
            ("No known history of substance abuse.", 0),
            ("Not a drug user.", 0),
            ("She reports no use of drugs.", 0),
            ("Never engaged in drug use.", 0),
            ("Zero illicit drug history.", 0),
            ("Not involved in substance use.", 0),
            ("No past or present drug use.", 0),
            ("Patient has never taken drugs.", 0),
            ("Clean from drug use.", 0),
            ("No drug experimentation.", 0),
            ("Patient claims total abstinence.", 0),
            ("Drug use: none.", 0),
            ("No substances reported.", 0),
            ("Never used heroin, meth, or similar.", 0),
            ("No narcotic history.", 0)
        ],
        "Attribution": [
            ("Patient denies drug use. Wife uses marijuana.", 0),
            ("Brother is an addict, patient is not.", 0),
            ("Mother uses opioids. Patient abstains.", 0),
            ("Roommate has history of drug use, patient clean.", 0),
            ("Partner smokes weed, patient does not.", 0),
            ("Patient reports sobriety; son uses drugs.", 0),
            ("Daughter in rehab, patient sober.", 0),
            ("Friend addicted to meth, patient avoids.", 0),
            ("Patient reports no use; roommate is user.", 0),
            ("Household uses drugs, patient does not.", 0),
            ("Lives with drug users but abstains.", 0),
            ("Nephew is addict, patient abstains.", 0),
            ("Spouse uses narcotics, not the patient.", 0),
            ("Sister has substance issues; patient denies use.", 0),
            ("Close relative uses heroin, patient never.", 0),
            ("Family drug history, no personal use.", 0),
            ("Patient avoids substances despite home exposure.", 0),
            ("Surrounded by users but stays clean.", 0),
            ("No use reported despite environment.", 0),
            ("Patient does not engage in use, despite access.", 0)
        ],
        "Historical Phrases": [
            ("Stopped opiates. Started again 1 month ago.", 2),
            ("Clean for years, relapsed recently.", 2),
            ("Patient resumed heroin use.", 2),
            ("Relapsed into drug use.", 2),
            ("Returned to cocaine after sobriety.", 2),
            ("Former addict, now using.", 2),
            ("Broke sobriety and started again.", 2),
            ("Was clean but relapsed last month.", 2),
            ("Previously sober, currently using.", 2),
            ("Patient is no longer abstinent.", 2),
            ("Back to methamphetamine.", 2),
            ("History of sobriety; now daily user.", 2),
            ("Patient is again using drugs.", 2),
            ("Was clean; resumed narcotics.", 2),
            ("No recent use until relapse.", 2),
            ("Drug use has resumed.", 2),
            ("Patient fell off recovery.", 2),
            ("Relapse confirmed after rehab.", 2),
            ("Abstinent no longer.", 2),
            ("Recovered, then relapsed.", 2)
        ],
        "Misspellings": [
            ("Pt dneies any drugs.", 0),
            ("No drug uze.", 0),
            ("Never usd narcatics.", 0),
            ("Denis heroin.", 0),
            ("No substnce abuse.", 0),
            ("Negativ for drug use.", 0),
            ("No cocane or metamphtmine.", 0),
            ("Histry of no drugs.", 0),
            ("Never takn illicit drgs.", 0),
            ("Abstanent from drugz.", 0),
            ("Never user of drgs.", 0),
            ("Says she dont use.", 0),
            ("Pt not using substanse.", 0),
            ("Narcitics: never.", 0),
            ("Drugz: none ever.", 0),
            ("No explcit abuse hist.", 0),
            ("Denes taking drugs.", 0),
            ("Non-usrr of drugs.", 0),
            ("Cocaine? Nver.", 0),
            ("Not partakng in drugs.", 0)
        ]
    }
}

# You can now import this file and access `test_bank` in your evaluation script.
